### PR TITLE
Create PKGBUILD

### PR DESCRIPTION
**Pull request by sc74**

### CODE REVIEW

**Comment by MattBlack85** [comment]
@sc74 it doesn't compile, I get this error

```
distcc[152959] Warning: failed to distribute mem.c to 10.0.1.47:3636/20, running locally instead
mem.c: In function ‘vm_i_byte’:
mem.c:581:12: error: implicit declaration of function ‘inb’; did you mean ‘ins’? [-Wimplicit-function-declaration]
  581 |     return inb(addr);
      |            ^~~
      |            ins
mem.c: In function ‘vm_i_word’:
mem.c:619:10: error: implicit declaration of function ‘inw’; did you mean ‘ins’? [-Wimplicit-function-declaration]
  619 |   return inw(addr);
      |          ^~~
      |          ins
mem.c: In function ‘vm_i_dword’:
mem.c:657:10: error: implicit declaration of function ‘inl’; did you mean ‘ins’? [-Wimplicit-function-declaration]
  657 |   return inl(addr);
      |          ^~~
      |          ins
mem.c: In function ‘vm_o_byte’:
mem.c:676:5: error: implicit declaration of function ‘outb’; did you mean ‘outs’? [-Wimplicit-function-declaration]
  676 |     outb(val, addr);
      |     ^~~~
      |     outs
mem.c: In function ‘vm_o_word’:
mem.c:711:3: error: implicit declaration of function ‘outw’; did you mean ‘outs’? [-Wimplicit-function-declaration]
  711 |   outw(val, addr);
      |   ^~~~
      |   outs
mem.c: In function ‘vm_o_dword’:
mem.c:748:3: error: implicit declaration of function ‘outl’; did you mean ‘outs’? [-Wimplicit-function-declaration]
  748 |   outl(val, addr);
      |   ^~~~
      |   outs
distcc[152959] ERROR: compile mem.c on localhost failed

```

**Comment by sc74** [comment]
Once again the io.h file is missing in the version of the glibc package for arm

**Comment by sc74** [comment]
The libx86EMU package can no longer be compiled on aarch64 because the io.h file no longer exists. It was removed because the I/O on x86 is not the same as on arm. I'm looking to get the hwinfo package without the libx86EMU package and see if Calamares works correctly with this modification

**Comment by sc74** [comment]
No need for libx86EMU package anymore
I close this pull request

**Pull request closed without merging**
